'use client';
import { useEffect, useState } from 'react';
import AppShell from '../components/AppShell';
const api = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';
export default function PromotionsPage() {
  const [rows,setRows]=useState([]),[message,setMessage]=useState(''),[form,setForm]=useState({code:'',name:'',discount_type:'percentage',discount_value:'',min_purchase:'',max_discount:'',usage_limit:''});
  const headers=()=>({'Content-Type':'application/json',Authorization:'Bearer '+localStorage.getItem('pos_access_token')});
  async function load(){const r=await fetch(api+'/promotions',{headers:headers()}),b=await r.json();if(!r.ok)throw Error(b.message);setRows(b.data);}
  useEffect(()=>{if(!localStorage.getItem('pos_access_token'))window.location.assign('/');else load().catch(e=>setMessage(e.message));},[]);
  async function save(e){e.preventDefault();try{const r=await fetch(api+'/promotions',{method:'POST',headers:headers(),body:JSON.stringify(form)}),b=await r.json();if(!r.ok)throw Error(b.message);setForm({code:'',name:'',discount_type:'percentage',discount_value:'',min_purchase:'',max_discount:'',usage_limit:''});setMessage('Promo disimpan.');load();}catch(e){setMessage(e.message);}}
  async function toggle(id){const r=await fetch(api+'/promotions/'+id+'/toggle-active',{method:'PUT',headers:headers()}),b=await r.json();if(!r.ok)return setMessage(b.message);load();}
  return <AppShell title="Promo & Diskon" eyebrow="PENJUALAN"><section className="product-grid"><form className="panel" onSubmit={save}><h2>Buat promo</h2><label>Kode promo<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="HEMAT10"/></label><label>Nama promo<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Jenis diskon<select value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})}><option value="percentage">Persentase (%)</option><option value="nominal">Nominal (Rp)</option></select></label><label>Nilai diskon<input required type="number" min="1" value={form.discount_value} onChange={e=>setForm({...form,discount_value:e.target.value})}/></label><label>Minimum belanja<input type="number" min="0" value={form.min_purchase} onChange={e=>setForm({...form,min_purchase:e.target.value})}/></label><label>Maksimum diskon (opsional)<input type="number" min="0" value={form.max_discount} onChange={e=>setForm({...form,max_discount:e.target.value})}/></label><label>Batas pemakaian (opsional)<input type="number" min="1" value={form.usage_limit} onChange={e=>setForm({...form,usage_limit:e.target.value})}/></label><button>Simpan promo</button>{message&&<p className="message">{message}</p>}</form><section className="panel"><h2>Daftar promo</h2><div className="product-list">{rows.map(p=><article key={p.id}><div><strong>{p.code} — {p.name}</strong><span>{p.discount_type==='percentage'?p.discount_value+'%':'Rp'+Number(p.discount_value).toLocaleString('id-ID')} · dipakai {p.usage_count}{p.usage_limit?'/'+p.usage_limit:''}</span></div><button type="button" onClick={()=>toggle(p.id)}>{p.is_active?'Nonaktifkan':'Aktifkan'}</button></article>)}{!rows.length&&<p>Belum ada promo.</p>}</div></section></section></AppShell>;
}
