'use client';
import { useEffect, useState } from 'react';
import AppShell from '../components/AppShell';
const api = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api'; const rupiah = (n) => `Rp${Number(n || 0).toLocaleString('id-ID')}`;
export default function OperationsPage() {
  const [report, setReport] = useState(null); const [drawer, setDrawer] = useState(null); const [opening, setOpening] = useState(''); const [actual, setActual] = useState(''); const [message, setMessage] = useState(''); const [closing, setClosing] = useState(null);
  const headers = () => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('pos_access_token')}` });
  async function load() { try { const [sales, cash] = await Promise.all([fetch(`${api}/reports/sales`, { headers: headers() }), fetch(`${api}/cash-drawer/summary`, { headers: headers() })]); const sb = await sales.json(); if (!sales.ok) throw new Error(sb.message); setReport(sb.data); if (cash.ok) setDrawer((await cash.json()).data); else setDrawer(null); } catch (e) { setMessage(e.message); } }
  useEffect(() => { if (!localStorage.getItem('pos_access_token')) window.location.assign('/'); else load(); }, []);
  async function open() { const r = await fetch(`${api}/cash-drawer/open`, { method: 'POST', headers: headers(), body: JSON.stringify({ opening_amount: Number(opening) }) }); const b = await r.json(); if (!r.ok) setMessage(b.message); else { setMessage('Laci kas dibuka.'); load(); } }
  async function close() { const r = await fetch(`${api}/cash-drawer/close`, { method: 'PUT', headers: headers(), body: JSON.stringify({ actual_cash: Number(actual) }) }); const b = await r.json(); if (!r.ok) setMessage(b.message); else { setClosing(b.data); setMessage(`Laci ditutup. Selisih ${rupiah(b.data.difference)}.`); load(); } }
  return <AppShell title="Operasional" eyebrow="KAS & TOKO"><section className="product-grid"><section className="panel"><h2>Penjualan Hari Ini</h2>{report ? <><strong className="big-number">{rupiah(report.gross_sales)}</strong><p>{report.transactions} transaksi · Diskon {rupiah(report.discounts)}</p><div className="product-list">{report.payments.map((p) => <article key={p.payment_method}><strong>{p.payment_method}</strong><strong>{rupiah(p.amount)}</strong></article>)}</div></> : <p>Memuat…</p>}</section><section className="panel"><h2>Laci Kas</h2>{drawer ? <><p>Modal: {rupiah(drawer.opening_amount)}</p><p>Kas seharusnya: <strong>{rupiah(drawer.expected_cash)}</strong></p><label>Kas aktual<input type="number" min="0" value={actual} onChange={(e) => setActual(e.target.value)} /></label><button onClick={close}>Tutup Laci</button></> : <><p>Belum ada laci kas terbuka.</p><label>Modal awal<input type="number" min="0" value={opening} onChange={(e) => setOpening(e.target.value)} /></label><button onClick={open}>Buka Laci</button></>}{closing && <p><a className="button-link" href={`/operations/closing/${closing.id}`} target="_blank">Cetak detail penutupan</a></p>}{message && <p className="message">{message}</p>}</section></section></AppShell>;
}
